//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceEngine.Data.EF.Questionnaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.Page1 = new HashSet<Page>();
            this.Rendered_Page = new HashSet<Rendered_Page>();
            this.Page_Question = new HashSet<Page_Question>();
        }
    
        public int Page_ID { get; set; }
        public int Page_Template_ID { get; set; }
        public int Scheme_ID { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<int> Next_Page_ID { get; set; }
    
        public virtual ICollection<Page> Page1 { get; set; }
        public virtual Page Page2 { get; set; }
        public virtual Page_Template Page_Template { get; set; }
        public virtual Scheme Scheme { get; set; }
        public virtual ICollection<Rendered_Page> Rendered_Page { get; set; }
        public virtual ICollection<Page_Question> Page_Question { get; set; }
    }
}
