//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceEngine.Data.EF.Questionnaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page_Question_Conditional_Display
    {
        public int Page_Question_Conditional_Display_ID { get; set; }
        public int Source_Page_Question_ID { get; set; }
        public int Target_Page_Question_ID { get; set; }
        public int Trigger_Question_Possible_Answer_ID { get; set; }
        public bool Hide { get; set; }
    
        public virtual Page_Question Page_Question { get; set; }
        public virtual Page_Question Page_Question1 { get; set; }
        public virtual Question_Possible_Answer Question_Possible_Answer { get; set; }
    }
}
