//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceEngine.Data.EF.Questionnaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page_Question
    {
        public Page_Question()
        {
            this.Page_Question_Conditional_Display = new HashSet<Page_Question_Conditional_Display>();
            this.Page_Question_Conditional_Display1 = new HashSet<Page_Question_Conditional_Display>();
            this.Page_Question_Validation = new HashSet<Page_Question_Validation>();
        }
    
        public int Page_Question_ID { get; set; }
        public int Page_ID { get; set; }
        public int Question_ID { get; set; }
        public int DisplayOrder { get; set; }
        public string QuestionText { get; set; }
        public string QuestionName { get; set; }
        public bool DefaultShow { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual ICollection<Page_Question_Conditional_Display> Page_Question_Conditional_Display { get; set; }
        public virtual ICollection<Page_Question_Conditional_Display> Page_Question_Conditional_Display1 { get; set; }
        public virtual Question Question { get; set; }
        public virtual ICollection<Page_Question_Validation> Page_Question_Validation { get; set; }
    }
}
