//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceEngine.Data.EF.Questionnaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page_Question_Validation
    {
        public int Page_Question_Validation_ID { get; set; }
        public int Page_Question_ID { get; set; }
        public int Validation_Type_ID { get; set; }
        public string ErrorMessage { get; set; }
        public string ValidationExpression { get; set; }
    
        public virtual Page_Question Page_Question { get; set; }
        public virtual Validation_Type Validation_Type { get; set; }
    }
}
