//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceEngine.Data.EF.Questionnaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_Possible_Answer
    {
        public Question_Possible_Answer()
        {
            this.Quote_Question_Answer = new HashSet<Quote_Question_Answer>();
            this.Page_Question_Conditional_Display = new HashSet<Page_Question_Conditional_Display>();
        }
    
        public int Question_Possible_Answer_ID { get; set; }
        public int Question_ID { get; set; }
        public string AnswerText { get; set; }
        public string AnswerValue { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ICollection<Quote_Question_Answer> Quote_Question_Answer { get; set; }
        public virtual ICollection<Page_Question_Conditional_Display> Page_Question_Conditional_Display { get; set; }
    }
}
