//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceEngine.Data.EF.Questionnaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Quote_Question_Answer = new HashSet<Quote_Question_Answer>();
            this.Question_Possible_Answer = new HashSet<Question_Possible_Answer>();
            this.Page_Question = new HashSet<Page_Question>();
        }
    
        public int Question_ID { get; set; }
        public int Scheme_ID { get; set; }
        public int Question_Template_ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    
        public virtual Question_Template Question_Template { get; set; }
        public virtual Scheme Scheme { get; set; }
        public virtual ICollection<Quote_Question_Answer> Quote_Question_Answer { get; set; }
        public virtual ICollection<Question_Possible_Answer> Question_Possible_Answer { get; set; }
        public virtual ICollection<Page_Question> Page_Question { get; set; }
    }
}
