//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceEngine.Data.EF.Questionnaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote_Question_Answer
    {
        public int Quote_Question_Answer_ID { get; set; }
        public int Quote_ID { get; set; }
        public int Question_ID { get; set; }
        public Nullable<int> Question_Possible_Answer_ID { get; set; }
        public string Answer { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual Question_Possible_Answer Question_Possible_Answer { get; set; }
    }
}
