//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceEngine.Data.EF.Questionnaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendered_Page
    {
        public int Rendered_Page_ID { get; set; }
        public int Page_ID { get; set; }
        public string PageContent { get; set; }
        public Nullable<System.DateTime> LastRenderDate { get; set; }
    
        public virtual Page Page { get; set; }
    }
}
