//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceEngine.Data.EF.Questionnaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Validation_Type
    {
        public Validation_Type()
        {
            this.Page_Question_Validation = new HashSet<Page_Question_Validation>();
        }
    
        public int Validation_Type_ID { get; set; }
        public string Name { get; set; }
        public string DataType { get; set; }
    
        public virtual ICollection<Page_Question_Validation> Page_Question_Validation { get; set; }
    }
}
